INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_0000', '0000 - Natureza Jurídica não informada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1015', '1015 - Órgão Público do Poder Executivo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1023', '1023 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1031', '1031 - Órgão Público do Poder Executivo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1040', '1040 - Órgão Público do Poder Legislativo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1058', '1058 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1066', '1066 - Órgão Público do Poder Legislativo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1074', '1074 - Órgão Público do Poder Judiciário Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1082', '1082 - Órgão Público do Poder Judiciário Estadual');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1104', '1104 - Autarquia Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1112', '1112 - Autarquia Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1120', '1120 - Autarquia Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1139', '1139 - Fundação Pública de Direito Público Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1147', '1147 - Fundação Pública de Direito Público Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1155', '1155 - Fundação Pública de Direito Público Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1163', '1163 - Órgão Público Autônomo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1171', '1171 - Órgão Público Autônomo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1180', '1180 - Órgão Público Autônomo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1198', '1198 - Comissão Polinacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1210', '1210 - Consórcio Público de Direito Público (Associação Pública)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1228', '1228 - Consórcio Público de Direito Privado');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1236', '1236 - Estado ou Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1244', '1244 - Município');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1252', '1252 - Fundação Pública de Direito Privado Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1260', '1260 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1279', '1279 - Fundação Pública de Direito Privado Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1287', '1287 - Fundo Público da Administração Indireta Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1295', '1295 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1309', '1309 - Fundo Público da Administração Indireta Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1317', '1317 - Fundo Público da Administração Direta Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1325', '1325 - Fundo Público da Administração Direta Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1333', '1333 - Fundo Público da Administração Direta Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_1341', '1341 - União');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2011', '2011 - Empresa Pública');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2038', '2038 - Sociedade de Economia Mista');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2046', '2046 - Sociedade Anônima Aberta');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2054', '2054 - Sociedade Anônima Fechada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2062', '2062 - Sociedade Empresária Limitada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2070', '2070 - Sociedade Empresária em Nome Coletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2089', '2089 - Sociedade Empresária em Comandita Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2097', '2097 - Sociedade Empresária em Comandita por Ações');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2100', '2100 - Sociedade Mercantil de Capital e Indústria');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2127', '2127 - Sociedade em Conta de Participação');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2135', '2135 - Empresário (Individual)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2143', '2143 - Cooperativa');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2151', '2151 - Consórcio de Sociedades');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2160', '2160 - Grupo de Sociedades');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2178', '2178 - Estabelecimento, no Brasil, de Sociedade Estrangeira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2194', '2194 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2216', '2216 - Empresa Domiciliada no Exterior');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2224', '2224 - Clube/Fundo de Investimento');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2232', '2232 - Sociedade Simples Pura');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2240', '2240 - Sociedade Simples Limitada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2259', '2259 - Sociedade Simples em Nome Coletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2267', '2267 - Sociedade Simples em Comandita Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2275', '2275 - Empresa Binacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2283', '2283 - Consórcio de Empregadores');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2291', '2291 - Consórcio Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2305', '2305 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2313', '2313 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2321', '2321 - Sociedade Unipessoal de Advocacia');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_2330', '2330 - Cooperativas de Consumo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3034', '3034 - Serviço Notarial e Registral (Cartório)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3069', '3069 - Fundação Privada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3077', '3077 - Serviço Social Autônomo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3085', '3085 - Condomínio Edilício');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3107', '3107 - Comissão de Conciliação Prévia');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3115', '3115 - Entidade de Mediação e Arbitragem');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3131', '3131 - Entidade Sindical');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3204', '3204 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3212', '3212 - Fundação ou Associação Domiciliada no Exterior');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3220', '3220 - Organização Religiosa');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3239', '3239 - Comunidade Indígena');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3247', '3247 - Fundo Privado');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3255', '3255 - Órgão de Direção Nacional de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3263', '3263 - Órgão de Direção Regional de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3271', '3271 - Órgão de Direção Local de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3280', '3280 - Comitê Financeiro de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3298', '3298 - Frente Plebiscitária ou Referendária');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3301', '3301 - Organização Social (OS)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_3999', '3999 - Associação Privada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_4014', '4014 - Empresa Individual Imobiliária');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_4090', '4090 - Candidato a Cargo Político Eletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_4120', '4120 - Produtor Rural (Pessoa Física)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_5010', '5010 - Organização Internacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_5029', '5029 - Representação Diplomática Estrangeira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_5037', '5037 - Outras Instituições Extraterritoriais');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CODE_8885', '8885 - Natureza Jurídica não informada');
