INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('NATUREZA_JURIDICA_NAO_INFORMADA', '0000/8885 - Natureza Jurídica não informada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_EXECUTIVO_FEDERAL', '1015 - Órgão Público do Poder Executivo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_EXECUTIVO_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1023 - Órgão Público do Poder Executivo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_EXECUTIVO_MUNICIPAL', '1031 - Órgão Público do Poder Executivo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_LEGISLATIVO_FEDERAL', '1040 - Órgão Público do Poder Legislativo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_LEGISLATIVO_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1058 - Órgão Público do Poder Legislativo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_LEGISLATIVO_MUNICIPAL', '1066 - Órgão Público do Poder Legislativo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_JUDICIARIO_FEDERAL', '1074 - Órgão Público do Poder Judiciário Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_DO_PODER_JUDICIARIO_ESTADUAL', '1082 - Órgão Público do Poder Judiciário Estadual');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('AUTARQUIA_FEDERAL', '1104 - Autarquia Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('AUTARQUIA_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1112 - Autarquia Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('AUTARQUIA_MUNICIPAL', '1120 - Autarquia Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PUBLICO_FEDERAL', '1139 - Fundação Pública de Direito Público Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PUBLICO_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1147 - Fundação Pública de Direito Público Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PUBLICO_MUNICIPAL', '1155 - Fundação Pública de Direito Público Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_AUTONOMO_FEDERAL', '1163 - Órgão Público Autônomo Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_AUTONOMO_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1171 - Órgão Público Autônomo Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_PUBLICO_AUTONOMO_MUNICIPAL', '1180 - Órgão Público Autônomo Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COMISSAO_POLINACIONAL', '1198 - Comissão Polinacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONSORCIO_PUBLICO_DE_DIREITO_PUBLICO_(ASSOCIACAO_PUBLICA)', '1210 - Consórcio Público de Direito Público (Associação Pública)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONSORCIO_PUBLICO_DE_DIREITO_PRIVADO', '1228 - Consórcio Público de Direito Privado');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ESTADO_OU_DISTRITO_FEDERAL', '1236 - Estado ou Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('MUNICIPIO', '1244 - Município');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PRIVADO_FEDERAL', '1252 - Fundação Pública de Direito Privado Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PRIVADO_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1260 - Fundação Pública de Direito Privado Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PUBLICA_DE_DIREITO_PRIVADO_MUNICIPAL', '1279 - Fundação Pública de Direito Privado Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_INDIRETA_FEDERAL', '1287 - Fundo Público da Administração Indireta Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_INDIRETA_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1295 - Fundo Público da Administração Indireta Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_INDIRETA_MUNICIPAL', '1309 - Fundo Público da Administração Indireta Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_DIRETA_FEDERAL', '1317 - Fundo Público da Administração Direta Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_DIRETA_ESTADUAL_OU_DO_DISTRITO_FEDERAL', '1325 - Fundo Público da Administração Direta Estadual ou do Distrito Federal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PUBLICO_DA_ADMINISTRACAO_DIRETA_MUNICIPAL', '1333 - Fundo Público da Administração Direta Municipal');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('UNIAO', '1341 - União');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_PUBLICA', '2011 - Empresa Pública');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_DE_ECONOMIA_MISTA', '2038 - Sociedade de Economia Mista');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_ANONIMA_ABERTA', '2046 - Sociedade Anônima Aberta');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_ANONIMA_FECHADA', '2054 - Sociedade Anônima Fechada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_EMPRESARIA_LIMITADA', '2062 - Sociedade Empresária Limitada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_EMPRESARIA_EM_NOME_COLETIVO', '2070 - Sociedade Empresária em Nome Coletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_EMPRESARIA_EM_COMANDITA_SIMPLES', '2089 - Sociedade Empresária em Comandita Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_EMPRESARIA_EM_COMANDITA_POR_ACOES', '2097 - Sociedade Empresária em Comandita por Ações');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_MERCANTIL_DE_CAPITAL_E_INDUSTRIA', '2100 - Sociedade Mercantil de Capital e Indústria');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_EM_CONTA_DE_PARTICIPACAO', '2127 - Sociedade em Conta de Participação');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESARIO_(INDIVIDUAL)', '2135 - Empresário (Individual)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COOPERATIVA', '2143 - Cooperativa');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONSORCIO_DE_SOCIEDADES', '2151 - Consórcio de Sociedades');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('GRUPO_DE_SOCIEDADES', '2160 - Grupo de Sociedades');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ESTABELECIMENTO,_NO_BRASIL,_DE_SOCIEDADE_ESTRANGEIRA', '2178 - Estabelecimento, no Brasil, de Sociedade Estrangeira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ESTABELECIMENTO,_NO_BRASIL,_DE_EMPRESA_BINACIONAL_ARGENTINO-BRASILEIRA', '2194 - Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_DOMICILIADA_NO_EXTERIOR', '2216 - Empresa Domiciliada no Exterior');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CLUBE/FUNDO_DE_INVESTIMENTO', '2224 - Clube/Fundo de Investimento');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_SIMPLES_PURA', '2232 - Sociedade Simples Pura');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_SIMPLES_LIMITADA', '2240 - Sociedade Simples Limitada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_SIMPLES_EM_NOME_COLETIVO', '2259 - Sociedade Simples em Nome Coletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_SIMPLES_EM_COMANDITA_SIMPLES', '2267 - Sociedade Simples em Comandita Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_BINACIONAL', '2275 - Empresa Binacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONSORCIO_DE_EMPREGADORES', '2283 - Consórcio de Empregadores');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONSORCIO_SIMPLES', '2291 - Consórcio Simples');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_INDIVIDUAL_DE_RESPONSABILIDADE_LIMITADA_(DE_NATUREZA_EMPRESARIA)', '2305 - Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_INDIVIDUAL_DE_RESPONSABILIDADE_LIMITADA_(DE_NATUREZA_SIMPLES)', '2313 - Empresa Individual de Responsabilidade Limitada (de Natureza Simples)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SOCIEDADE_UNIPESSOAL_DE_ADVOCACIA', '2321 - Sociedade Unipessoal de Advocacia');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COOPERATIVAS_DE_CONSUMO', '2330 - Cooperativas de Consumo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SERVICO_NOTARIAL_E_REGISTRAL_(CARTORIO)', '3034 - Serviço Notarial e Registral (Cartório)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_PRIVADA', '3069 - Fundação Privada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('SERVICO_SOCIAL_AUTONOMO', '3077 - Serviço Social Autônomo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CONDOMINIO_EDILICIO', '3085 - Condomínio Edilício');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COMISSAO_DE_CONCILIACAO_PREVIA', '3107 - Comissão de Conciliação Prévia');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ENTIDADE_DE_MEDIACAO_E_ARBITRAGEM', '3115 - Entidade de Mediação e Arbitragem');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ENTIDADE_SINDICAL', '3131 - Entidade Sindical');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ESTABELECIMENTO,_NO_BRASIL,_DE_FUNDACAO_OU_ASSOCIACAO_ESTRANGEIRAS', '3204 - Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDACAO_OU_ASSOCIACAO_DOMICILIADA_NO_EXTERIOR', '3212 - Fundação ou Associação Domiciliada no Exterior');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGANIZACAO_RELIGIOSA', '3220 - Organização Religiosa');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COMUNIDADE_INDIGENA', '3239 - Comunidade Indígena');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FUNDO_PRIVADO', '3247 - Fundo Privado');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_DE_DIRECAO_NACIONAL_DE_PARTIDO_POLITICO', '3255 - Órgão de Direção Nacional de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_DE_DIRECAO_REGIONAL_DE_PARTIDO_POLITICO', '3263 - Órgão de Direção Regional de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGAO_DE_DIRECAO_LOCAL_DE_PARTIDO_POLITICO', '3271 - Órgão de Direção Local de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('COMITE_FINANCEIRO_DE_PARTIDO_POLITICO', '3280 - Comitê Financeiro de Partido Político');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('FRENTE_PLEBISCITARIA_OU_REFERENDARIA', '3298 - Frente Plebiscitária ou Referendária');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGANIZACAO_SOCIAL_(OS)', '3301 - Organização Social (OS)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ASSOCIACAO_PRIVADA', '3999 - Associação Privada');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('EMPRESA_INDIVIDUAL_IMOBILIARIA', '4014 - Empresa Individual Imobiliária');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('CANDIDATO_A_CARGO_POLITICO_ELETIVO', '4090 - Candidato a Cargo Político Eletivo');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('PRODUTOR_RURAL_(PESSOA_FISICA)', '4120 - Produtor Rural (Pessoa Física)');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('ORGANIZACAO_INTERNACIONAL', '5010 - Organização Internacional');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('REPRESENTACAO_DIPLOMATICA_ESTRANGEIRA', '5029 - Representação Diplomática Estrangeira');
INSERT INTO PUBLIC."ENaturezasJuridicas" ("valor", "descricao") VALUES ('OUTRAS_INSTITUICOES_EXTRATERRITORIAIS', '5037 - Outras Instituições Extraterritoriais');
