export enum EQualificacaoSocios {
  'CODIGO' = 0,
  'DESCRICAO' = 1
}

export enum EPaises {
  'CODIGO' = 0,
  'DESCRICAO' = 1
}

export enum EMunicipios {
  'CODIGO' = 0,
  'DESCRICAO' = 1
}

export enum ENaturezasJuridicas {
  'CODIGO' = 0,
  'DESCRICAO' = 1
}

export enum ECNAEs {
  'CODIGO' = 0,
  'DESCRICAO' = 1
}

export enum EEstabelecimentos {
  'CNPJ_BASICO' = 0,
  'CNPJ_ORDEM' = 1,
  'CNPJ_DV' = 2,
  'IDENTIFICADOR' = 3,
  'NOME_FANTASIA' = 4,
  'SITUACAO_CADASTRAL' = 5,
  'DATA_SITUACAO_CADASTRAL' = 6,
  'MOTIVO_SITUACAO_CADASTRAL' = 7,
  'NOME_DA_CIDADE_NO_EXTERIOR' = 8,
  'PAIS' = 9,
  'DATA_DE_INICIO_ATIVIDADE' = 10,
  'CNAE_FISCAL_PRINCIPAL' = 11,
  'CNAE_FISCAL_SECUNDARIA' = 12,
  'TIPO_DE_LOGRADOURO' = 13,
  'LOGRADOURO' = 14,
  'NUMERO' = 15,
  'COMPLEMENTO' = 16,
  'BAIRRO' = 17,
  'CEP' = 18,
  'UF' = 19,
  'MUNICIPIO' = 20,
  'DDD_1' = 21,
  'TELEFONE_1' = 22,
  'DDD_2' = 23,
  'TELEFONE_2' = 24,
  'DDD_FAX' = 25,
  'FAX' = 26,
  'CORREIO_ELETRONICO' = 27,
  'SITUACAO_ESPECIAL' = 28,
  'DATA_DA_SITUACAO_ESPECIAL' = 29
}

export enum ESocios {
  'CNPJ_BASICO' = 0,
  'IDENTIFICADOR_DE_SOCIO' = 1,
  'NOME_DO_SOCIO' = 2,
  'CNPJ_CPF_DO_SOCIO' = 3,
  'QUALIFICACAO_DO_SOCIO' = 4,
  'DATA_DE_ENTRADA_SOCIEDADE' = 5,
  'PAIS' = 6,
  'REPRESENTANTE_LEGAL' = 7,
  'NOME_DO_REPRESENTANTE' = 8,
  'QUALIFICACAO_DO_REPRESENTANTE_LEGAL' = 9,
  'FAIXA_ETARIA' = 10
}

export enum EEmpresas {
  'CNPJ_BASICO' = 0,
  'RAZAO_SOCIAL_NOME_EMPRESARIAL' = 1,
  'NATUREZA_JURIDICA' = 2,
  'QUALIFICACAO_DO_RESPONSAVEL' = 3,
  'CAPITAL_SOCIAL_DA_EMPRESA' = 4,
  'PORTE_DA_EMPRESA' = 5,
  'ENTE_FEDERATIVO_RESPONSAVEL' = 6,
}
