-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO PUBLIC."EPorteEmpresa" ("valor", "descricao") VALUES ('CODE_1', '1 – NÃO INFORMADO');
-- INSERT INTO PUBLIC."EPorteEmpresa" ("valor", "descricao") VALUES ('CODE_2', '2 - MICRO EMPRESA');
-- INSERT INTO PUBLIC."EPorteEmpresa" ("valor", "descricao") VALUES ('CODE_03', '03 - EMPRESA DE PEQUENO PORTE');
-- INSERT INTO PUBLIC."EPorteEmpresa" ("valor", "descricao") VALUES ('CODE_05', '05 - DEMAIS');
