-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO PUBLIC."ETipoPessoaJuridica" ("valor", "descricao") VALUES ('CODE_01', 'MATRIZ');
-- INSERT INTO PUBLIC."ETipoPessoaJuridica" ("valor", "descricao") VALUES ('CODE_02', 'FILIAL');
