export interface Socio {
  tipoRegistro: string | null;
  indicadorFullDiario: string | null;
  tipoAtualizacao: string | null;
  cnpj: string | null;
  identificador: string | null;
  nomeRazaoSocial: string | null;
  cpfCnpj: string | null;
  qualificacao: string | null;
  percentualCapitalSocial: string | null;
  dataEntradaSociedade: string | null;
  codigoPais: string | null;
  nomePais: string | null;
  cpfRepLegal: string | null;
  nomeRep: string | null;
  qualificacaoRepLegal: string | null;
  filler: string | null;
  fimRegistro: string | null;
}
