-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO PUBLIC."ETipoSituacoesCadastrais" ("valor", "descricao") VALUES ('CODE_01', '01 – NULA');
-- INSERT INTO PUBLIC."ETipoSituacoesCadastrais" ("valor", "descricao") VALUES ('CODE_02', '2 – ATIVA');
-- INSERT INTO PUBLIC."ETipoSituacoesCadastrais" ("valor", "descricao") VALUES ('CODE_03', '3 – SUSPENSA');
-- INSERT INTO PUBLIC."ETipoSituacoesCadastrais" ("valor", "descricao") VALUES ('CODE_04', '4 – INAPTA');
-- INSERT INTO PUBLIC."ETipoSituacoesCadastrais" ("valor", "descricao") VALUES ('CODE_08', '08 – BAIXADA');
