INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_00', '00 - Não informada');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_05', '05 - Administrador');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_08', '08 - Conselheiro de Administração');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_09', '09 - Curador');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_10', '10 - Diretor');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_11', '11 - Interventor');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_12', '12 - Inventariante');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_13', '13 - Liquidante');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_14', '14 - Mãe');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_15', '15 - Pai');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_16', '16 - Presidente');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_17', '17 - Procurador');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_18', '18 - Secretário');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_19', '19 - Síndico (Condomínio)');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_20', '20 - Sociedade Consorciada');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_21', '21 - Sociedade Filiada');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_22', '22 - Sócio');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_23', '23 - Sócio Capitalista');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_24', '24 - Sócio Comanditado');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_25', '25 - Sócio Comanditário');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_26', '26 - Sócio de Indústria');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_28', '28 - Sócio-Gerente');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_29', '29 - Sócio Incapaz ou Relat.Incapaz (exceto menor)');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_30', '30 - Sócio Menor (Assistido/Representado)');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_31', '31 - Sócio Ostensivo');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_32', '32 - Tabelião');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_33', '33 - Tesoureiro');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_34', '34 - Titular de Empresa Individual Imobiliária');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_35', '35 - Tutor');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_37', '37 - Sócio Pessoa Jurídica Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_38', '38 - Sócio Pessoa Física Residente no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_39', '39 - Diplomata');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_40', '40 - Cônsul');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_41', '41 - Representante de Organização Internacional');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_42', '42 - Oficial de Registro');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_43', '43 - Responsável');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_46', '46 - Ministro de Estado das Relações Exteriores');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_47', '47 - Sócio Pessoa Física Residente no Brasil');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_48', '48 - Sócio Pessoa Jurídica Domiciliado no Brasil');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_49', '49 - Sócio-Administrador');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_50', '50 - Empresário');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_51', '51 - Candidato a cargo Político Eletivo');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_52', '52 - Sócio com Capital');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_53', '53 - Sócio sem Capital');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_54', '54 - Fundador');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_55', '55 - Sócio Comanditado Residente no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_56', '56 - Sócio Comanditário Pessoa Física Residente no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_57', '57 - Sócio Comanditário Pessoa Jurídica Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_58', '58 - Sócio Comanditário Incapaz');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_59', '59 - Produtor Rural');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_60', '60 - Cônsul Honorário');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_61', '61 - Responsável indígena');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_62', '62 - Representante da Instituição Extraterritorial');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_63', '63 - Cotas em Tesouraria');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_64', '64 - Administrador Judicial');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_65', '65 - Titular Pessoa Física Residente ou Domiciliado no Brasil');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_66', '66 - Titular Pessoa Física Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_67', '67 - Titular Pessoa Física Incapaz ou Relativamente Incapaz (exceto menor)');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_68', '68 - Titular Pessoa Física Menor (Assistido/Representado)');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_69', '69 - Beneficiário Final');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_70', '70 - Administrador Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_71', '71 - Conselheiro de Administração Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_72', '72 - Diretor Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_73', '73 - Presidente Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_74', '74 - Sócio-Administrador Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_75', '75 - Fundador Residente ou Domiciliado no Exterior');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_78', '78 - Titular Pessoa Jurídica Domiciliada no Brasil');
INSERT INTO PUBLIC."EQualificacaoSocios" ("valor", "descricao") VALUES ('CODE_79', '79 - Titular Pessoa Jurídica Domiciliada no Exterior');
